### ISSUE TITLE
Windows version?

### ISSUE THREAD

**Issue by Keksstar** [DrewLX/StreamdeckPro#2]
Actually the StreamdeckPro is developed for OSX. Any change to get it also for Windows?
The whole project looks really promissing :)

**Comment by DrewLX** [comment]
I do plan on releasing a windows build eventually. If you wanted to try compiling it on a windows computer I'd be happy to help guide you through this.

Install Node.js and NPM
Download the zip source code for the project. 
Navigate to the folder in the command prompt
do: `npm install`
then: `npm run dev`

See what happens!

**Comment by Keksstar** [comment]
Hey Drew,

thanks for that! I will try it

Regards,
Andy

**Comment by Keksstar** [comment]
Sadly it´s not working...

Output after npm install:
```
Windows PowerShell
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

PS C:\Users\Andreas> cd Downloads
PS C:\Users\Andreas\Downloads> cd StreamdeckPro-0.2.0
PS C:\Users\Andreas\Downloads\StreamdeckPro-0.2.0> npm install

> sharp@0.18.4 install C:\Users\Andreas\Downloads\StreamdeckPro-0.2.0\node_modules\elgato-stream-deck\node_modules\sharp> node-gyp rebuild


C:\Users\Andreas\Downloads\StreamdeckPro-0.2.0\node_modules\elgato-stream-deck\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:170:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Andreas\Downloads\StreamdeckPro-0.2.0\node_modules\elgato-stream-deck\node_modules\sharp
gyp ERR! node -v v9.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN streamdeck-pro@0.2.0 No repository field.
npm WARN streamdeck-pro@0.2.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.18.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.18.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Andreas\AppData\Roaming\npm-cache\_logs\2018-04-08T16_22_06_332Z-debug.log
PS C:\Users\Andreas\Downloads\StreamdeckPro-0.2.0>
```


Output after npm run dev:
```
PS C:\Users\Andreas\Downloads\StreamdeckPro-0.2.0> npm run dev

> streamdeck-pro@0.2.0 dev C:\Users\Andreas\Downloads\StreamdeckPro-0.2.0
> node .electron-vue/dev-runner.js

C:\Users\Andreas\Downloads\StreamdeckPro-0.2.0\node_modules\electron\index.js:9
  throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
  ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at Object.<anonymous> (C:\Users\Andreas\Downloads\StreamdeckPro-0.2.0\node_modules\electron\index.js:9:9)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (C:\Users\Andreas\Downloads\StreamdeckPro-0.2.0\.electron-vue\dev-runner.js:4:18)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! streamdeck-pro@0.2.0 dev: `node .electron-vue/dev-runner.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the streamdeck-pro@0.2.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Andreas\AppData\Roaming\npm-cache\_logs\2018-04-08T16_25_03_405Z-debug.log
PS `C:\Users\Andreas\Downloads\StreamdeckPro-0.2.0>

```

**Comment by JatheJester** [comment]
Very much looking forward to a windows release as well. an OSC interface for the stream deck would be extremely useful for my application of the device.

**Comment by Rzbck** [comment]
Very good project ! 
Sadly im a windows users but sometimes for work i use both so ...
Tommorow i go read deeper in your project
but for my personnal use of convertting midi to OSC so trigger event on network
i also need to trigger both OSC message and midi message to communicate with 2 machine 
One one midi and the copy over network !
I ll try your plugin soon on mac ;)

**Comment by DrewLX** [comment]
I gave up on this project and just use Bitfocus.io Companion

Drew Perry

*___________*
07737 206091
<http://www.amplifyvideo.co.uk/>www.drewperry.co.uk
